apiVersion: v1
kind: ReplicationController
metadata:
  name: postgresql
  namespace: wisdom
spec:
  replicas: 1
  selector:
    name: postgresql
  template:
    metadata:
      name: postgresql
      labels:
        name: postgresql
    spec:
      containers:
      - name: postgresql
        image: sameersbn/postgresql:10
        env:
        - name: DB_USER
          value: juxtagene
        - name: DB_PASS
          value: qwer1234
        - name: DB_NAME
          value: api-db
        - name: DB_EXTENSION
          value: 'pg_trgm,btree_gist'
        - name: TZ
          value: Asia/Seoul
        ports:
        - name: postgres
          containerPort: 5432
        # volumeMounts:
        # - mountPath: /var/lib/postgresql
        #   name: api-postgresql-app-pv
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - localhost
            - -U 
            - postgres
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - localhost
            - -U 
            - postgres
          initialDelaySeconds: 5
          timeoutSeconds: 1
      # volumes:
      #   - name: api-postgresql-app-pv
      #     persistentVolumeClaim:
      #       claimName: api-postgresql-app-pvc
