apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-postgresql-app-pvc
  namespace: wisdom
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
