#
# 이 파일은 도커를 관리하는 파일입니다. 
#
version: '2'
services:
    kafka-redis-publisher:
        build:
            context     : ./
            dockerfile  : Dockerfile
        image           : ${DOCKER_PATH}/${DOCKER_IMG_NAME}:${DOCKER_IMG_TAG}
        platform: linux/amd64
