#
# 이 파일은 도커를 관리하는 파일입니다. 
#
version: '2'
services:
    allso-services-backend-monitor:
        build:
            context     : ./
            dockerfile  : Dockerfile
        image           : services/allso-backend-monitor:latest