apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-allso
  namespace: allso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-allso
  template:
    metadata:
      labels:
        app: frontend-allso
    spec:
      containers:
      - name: frontend-allso
        image: az.docker.juxtagene.com/services/allso-frontend-monitor:latest
        imagePullPolicy: Always
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      imagePullSecrets:
      - name: juxtagene-docker-registry
      restartPolicy: Always