apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  namespace: monitor
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-allso
    cert-manager.io/acme-challenge-type: http01
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: az.allso.juxtagene.com
    http:
      paths:
        - backend:
            service:
              name: frontend
              port:
                number: 80
          path: /
          pathType: Prefix
  tls:
  - hosts:
    - az.allso.juxtagene.com
    secretName: az-allso-juxtagene-com-tls