apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: allso
  annotations:
    # nginx.org/websocket-services: "frontend"
    # nginx.ingress.kubernetes.io/proxy-body-size: "0"
    # nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    # nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    cert-manager.io/cluster-issuer: letsencrypt-prod-allso
    cert-manager.io/acme-challenge-type: http01
spec:
  rules:
  - host: az.allso.juxtagene.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: frontend
            port:
              number: 80
  tls:
  - hosts:
    - az.allso.juxtagene.com
    secretName: az-allso-juxtagene-com-tls