apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: allso
resources:
  - deployment.yaml
  - docker-registry.yaml
  - ingress.yaml
  - issuer.yaml
  - namespace.yaml
  - service.yaml