apiVersion: v1
kind: Secret
metadata:
  name: main-cluster
  labels:
    argocd.argoproj.io/secret-type: cluster
  namespace: argocd
type: Opaque
stringData:
  name: main
  server: https://rancher.seegene.com/k8s/clusters/p-p6gdk
  config: |
    {
      "bearerToken": "token-7sh8g:vs85mr22tbkv55wmkdflzphclx72ttq6grbbpg2pjskk82f7pwrq6d",
        "tlsClientConfig": {
          "insecure": false
        }
    }

# https://rancher.nemopai.com/v3

# token-tkp8c
# hfj66shfz9q9rwx559qbkfzx85wsjzgwcqttc8j5h6hxdpk46srz4n
# token-tkp8c:hfj66shfz9q9rwx559qbkfzx85wsjzgwcqttc8j5h6hxdpk46srz4n
