apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: binding-ssh-to-topic
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: ssh-source
    properties:
      connectionHost: ""
      connectionPort: 22
      password: ""
      username: ""
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: topic-sink
