apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: slack-sink-binding
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: kafka-ssh-topic
    properties:
      bootstrapServers: "kafka:9092"
      topic: test-ssh02
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: slack-sink
    properties:
      channel: "#kafkaconnect-demo"
      webhookUrl: https://hooks.slack.com/services/T0ffkspasfksap
