
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: dockerui-juxtagene-com
  namespace: docker
spec:
  secretName: dockerui-juxtagene-com-tls
  issuerRef:
    name: letsencrypt-prod
  commonName: dockerui.juxtagene.com
  dnsNames:
  - dockerui.juxtagene.com

