apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: elastic
  labels:
    k8s-app: fluentd-logging
    version: v1
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-logging
      version: v1
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
#      imagePullSecrets: 
#      - name: insilico-docker-registry
      containers:
      - name: fluentd
        #image: docker.seegene.com/elk/fluentd-image:0.2
        image: 1223yys/fluentd-kafka:latest
        env:
          - name: FLUENT_KAFKA_BROKERS
            #value: "kafka-proj.kafka-c.svc.cluster.local:9092"
            value: "kafka.kafka:9092"
          - name: FLUENT_KAFKA_DEFAULT_TOPIC
            #value: "test"
            value: "fluentd-container-logging"
          - name: FLUENT_KAFKA_OUTPUT_DATA_TYPE
            value: "json"
          - name: FLUENT_KAFKA_COMPRESSION_CODEC
            value: "snappy"
          - name: FLUENT_KAFKA_MAX_SEND_LIMIT_BYTES
            value: "4096"
        resources:
          limits:
          requests:
            #cpu: 100m
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
